version: "3.9"
networks:
  desafio-net:
    driver: bridge

volumes:
  database-data:
    driver: local

services:
  web:
    build: .
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
    ports:
      - 3000:3000
    networks:
      - desafio-net
    depends_on:
      - database
  
  database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=gcb_test
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    ports: 
     -  3306:3306
    networks:
      - desafio-net
    volumes:
      - database-data:/var/lib/mysql
    restart: unless-stopped